library(tidyverse)

# Reclassify all clusters for whom id and log2 classification differed (reclassifications based on visualization see supp figure 6 and 7)
# Cluster numbers refer to original cluster numbers and not to ordered cluster number (as in the figures in supplementary files)
df <- df %>% 
  mutate(n_ab_class = case_when(group == 0 | group == 2 | group ==3 ~ group_final, 
                             (as_clusters_id == 0 & as_clusters_log == 0) ~ 'decreasing', 
                             (as_clusters_id == 0 & as_clusters_log == 1) ~ 'increasing', 
                             (as_clusters_id == 0 & as_clusters_log == 4) ~ 'increasing', 
                             (as_clusters_id == 0 & as_clusters_log == 10) ~ 'decreasing', 
                             (as_clusters_id == 0 & as_clusters_log == 11) ~ 'increasing', 
                             (as_clusters_id == 1 & as_clusters_log == 0) ~ 'decreasing', 
                             (as_clusters_id == 1 & as_clusters_log == 4) ~ 'increasing', 
                             (as_clusters_id == 2 & as_clusters_log == 0) ~ 'increasing', 
                             (as_clusters_id == 2 & as_clusters_log == 1) ~ 'increasing', 
                             (as_clusters_id == 2 & as_clusters_log == 7) ~ 'increasing', 
                             (as_clusters_id == 2 & as_clusters_log == 9) ~ 'increasing', 
                             (as_clusters_id == 2 & as_clusters_log == 10) ~ 'increasing', 
                             (as_clusters_id == 2 & as_clusters_log == 12) ~ 'increasing', 
                             (as_clusters_id == 3 & as_clusters_log == 1) ~ 'de- and increasing', 
                             (as_clusters_id == 4 & as_clusters_log == 1) ~ 'increasing', 
                             (as_clusters_id == 4 & as_clusters_log == 7) ~ 'increasing',
                             (as_clusters_id == 4 & as_clusters_log == 10) ~ 'de- and increasing', 
                             (as_clusters_id == 5 & as_clusters_log == 2) ~ 'increasing', 
                             (as_clusters_id == 5 & as_clusters_log == 4) ~ 'increasing', 
                             (as_clusters_id == 5 & as_clusters_log == 6) ~ 'increasing', 
                             (as_clusters_id == 5 & as_clusters_log == 7) ~ 'increasing',
                             (as_clusters_id == 5 & as_clusters_log == 10) ~ 'de- and increasing', 
                             (as_clusters_id == 5 & as_clusters_log == 11) ~ 'de- and increasing', 
                             (as_clusters_id == 5 & as_clusters_log == 12) ~ 'de- and increasing', 
                             (as_clusters_id == 6 & as_clusters_log == 1) ~ 'de- and increasing', 
                             (as_clusters_id == 6 & as_clusters_log == 3) ~ 'decreasing', 
                             (as_clusters_id == 6 & as_clusters_log == 7) ~ 'decreasing', 
                             (as_clusters_id == 7 & as_clusters_log == 0) ~ 'increasing', 
                             (as_clusters_id == 7 & as_clusters_log == 1) ~ 'increasing', 
                             (as_clusters_id == 7 & as_clusters_log == 3) ~ 'increasing', 
                             (as_clusters_id == 7 & as_clusters_log == 5) ~ 'increasing', 
                             (as_clusters_id == 7 & as_clusters_log == 7) ~ 'increasing', 
                             (as_clusters_id == 7 & as_clusters_log == 9) ~ 'increasing', 
                             (as_clusters_id == 7 & as_clusters_log == 10) ~ 'increasing', 
                             (as_clusters_id == 8 & as_clusters_log == 0) ~ 'decreasing', 
                             (as_clusters_id == 8 & as_clusters_log == 4) ~ 'increasing', 
                             (as_clusters_id == 8 & as_clusters_log == 11) ~ 'increasing',
                             (as_clusters_id == 9 & as_clusters_log == 1) ~ 'decreasing', 
                             (as_clusters_id == 9 & as_clusters_log == 7) ~ 'de- and increasing', 
                             (as_clusters_id == 9 & as_clusters_log == 11) ~ 'de- and increasing', 
                             (as_clusters_id == 11 & as_clusters_log == 1) ~ 'decreasing', 
                             (as_clusters_id == 11 & as_clusters_log == 6) ~ 'de- and increasing', 
                             (as_clusters_id == 11 & as_clusters_log == 7) ~ 'decreasing'))

